### ISSUE TITLE
fix: update deprecated FP8/BF8 API usage in example files

### ISSUE THREAD

**Issue by mvillmow** [HomericIntelligence/ProjectOdyssey#4515]
## Objective

Fix deprecated API usage in FP8/BF8 example files that reference removed `DType.from_float32()`.

## Problem

\`\`\`
examples/fp8_example.mojo:27: error: 'DType' value has no attribute 'from_float32'
\`\`\`

## Files Affected

- `examples/fp8_example.mojo`
- `examples/bf8_example.mojo` (likely same issue)

## Success Criteria

- [ ] Files compile with current Mojo v0.26.1 API
- [ ] FP8/BF8 examples still demonstrate the intended functionality

## Notes

`DType.from_float32()` was removed in a Mojo update. Need to find the replacement API.
